### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by savaukr** [savaukr/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by savaukr** [comment]
https://www.facebook.com/sava.ukr
sava_ukr@ukr.net

**Comment by savabinary** [comment]
https://www.facebook.com/sava.ukr
sava_ukr@ukr.net
097-412-49-50
